# Riptide example system configuration file.
riptide:
  proxy:
    url: riptide.local
    ports:
      http: 80
      https: 443
    autostart: true

  repos: []
  update_hosts_file: true

  engine: docker
